### PR TITLE
Added the blog link in README.md.

### PR DESCRIPTION
**Pull request by mynameissaraah**
An intuitive blog that also allows beginners to understand how they can create a developer account and start testing out and integrating with Chimoney

### CODE REVIEW

**Review by phyleria — CHANGES_REQUESTED** [review]
Hi @mynameissaraah 

For developers looking to test the API they should create an account here: https://sandbox.chimoney.io/developers not on https://dash.chimoney.io/ 

KIndly update this with the right sign up process. Thank you

**Comment by mynameissaraah** [comment]
Ok I will. Should I take out https://dash.chimoney.io/ totally?

**Comment by phyleria** [comment]
> Ok I will. Should I take out https://dash.chimoney.io/ totally?

Yes

**Comment by mynameissaraah** [comment]
Ok I will do just that.

**Review by uchibeke — APPROVED** [review]

**Review by phyleria — COMMENTED** [review]
LGTM 🎉

**Review by phyleria — APPROVED** [review]

**Pull request merged**
