### PR TITLE
Added a new article  [ Hacktoberfest]

### PR DESCRIPTION
**Pull request by neelshah2409**
Added an article on how to integrate mobile app with Chimoney.

### CODE REVIEW

**Comment by uchibeke** [comment]
This article has been added before. Why submit the same thing twice?

**Comment by neelshah2409** [comment]
@uchibeke you can read the article once please ,the previous article was with integrating mobile app with  chimoney API and I have explanied around Chimoney webhhoks.

**Comment by uchibeke** [comment]
Apologies @neelshah2409 .

**Review by uchibeke — APPROVED** [review]
LGTM 🚀

**Comment by neelshah2409** [comment]
Hey @uchibeke ,is there any reward for the PR in hacktoberfest and if yes how could I redeem it.

**Comment by uchibeke** [comment]
@Regedit-msc

**Pull request merged**
