### PR TITLE
Adding Hindi as a language in the README

### PR DESCRIPTION
**Pull request by vinfinity7**
This PR fixes issue #400 
@phyleria kindly review 👍

### CODE REVIEW

**Comment by phyleria** [comment]
Ok ✅

**Comment by vinfinity7** [comment]
@phyleria consider merging if everything seems alright

**Review by phyleria — APPROVED** [review]
LGTM 🎉

**Comment by vinfinity7** [comment]
@phyleria How am i gonna claim the reward?

**Pull request merged**
