### PR TITLE
add icons to the repo

### PR DESCRIPTION
**Pull request by kimanigitau01**
**Problem:** 
the repository does not have an appropriate method of visualizing its activity
**solution:**
add _icons_  from [shields](https://shields.io/) the top of the repository giving details about the repository's activity

### CODE REVIEW

**Comment by phyleria** [comment]
Hi @kimanigitau01 

What issue did you work on?

**Comment by kimanigitau01** [comment]
Just added icons to the readme to visualise more on the progress of the repository

**Comment by phyleria** [comment]
What's the issue number?

**Comment by kimanigitau01** [comment]
#**151**

**Comment by phyleria** [comment]
Hi @kimanigitau01 

It's not clear what you worked on, the issue you mentioned doesn't align with your PR. I'll close this for now.

**Pull request closed without merging**
