### PR TITLE
Refactoring handleWebhook to Improve Readability, Error Handling, and Modularity

### PR DESCRIPTION
**Pull request by HarshMN2345**
The handleWebhook function in the webhook handler needs a refactor to improve code readability and ensure better error handling. This will include:

Implementing early return guard clauses for better flow control.
Enhancing error logging and response handling for various scenarios.
Keeping the core logic cleaner by using helper functions where applicable.

### CODE REVIEW

**Comment by HarshMN2345** [comment]
@uchibeke i have added a PR to separate error handling logic from the main webhook handler

**Comment by HarshMN2345** [comment]
@phyleria  i have added a PR,please check and review

**Review by phyleria — COMMENTED** [review]
Hi @HarshMN2345 ,

Thanks for updating the handleWebhook function! The code looks cleaner with the improved structure. Before we merge, here are a few final suggestions:

- Consider using a logging library like Winston instead of console.error. This will make error tracking easier in production environments.

- It may help to add additional context to errors. For example, including the issueID in res.status(404).json when no transaction is found will assist in tracking down specific issues.

- Adding a few high-level comments to describe the main sections of this function (e.g., verifying webhooks, fetching transactions) would help make the code even more approachable for future contributors.

Thanks again for your hard work on this! Once these minor updates are made, we’ll be ready to merge.

**Comment by HarshMN2345** [comment]
@phyleria Thank you for reviewing the handleWebhook function and for your valuable feedback! I’ve made the suggested updates,The updated code should now be clearer and more robust. Thanks again for your helpful insights!

**Review by phyleria — APPROVED** [review]
LGTM 🎉

**Pull request merged**
