### PR TITLE
Improved Homepage of redeem Airtime 

### PR DESCRIPTION
**Pull request by ayan-joshi**
Closing the issue #457 

image

gave it better styling and alignment. 
have a look @phyleria

### CODE REVIEW

**Comment by ayan-joshi** [comment]
@phyleria have a look

**Comment by ayan-joshi** [comment]
@phyleria have a look

**Comment by phyleria** [comment]
Hi @ayan-joshi, thank you for this!

Could you please share a screenshot of how the page looked before? Much appreciated!

**Comment by ayan-joshi** [comment]
> Hi @ayan-joshi, thank you for this!
> 
> Could you please share a screenshot of how the page looked before? Much appreciated!

@phyleria here it is before

**Comment by phyleria** [comment]
Awesome, thanks!

Please change the name to `Keeplite` and it should be good to go.

**Comment by ayan-joshi** [comment]
> Awesome, thanks!
> 
> Please change the name to `Keeplite` and it should be good to go.

my bad , I'll fix this

**Review by phyleria — APPROVED** [review]
LGTM 🎉

**Pull request merged**
