### PR TITLE
[hacktoberfest] feat: Complete chi money js 

### PR DESCRIPTION
**Pull request by Ayo-Awe**
This PR completely implements the chimoneyjs sdk
All modules have been fully implemented at issue #11. The include
- Account 
- Payouts
- Redeem
- Mobile Money
- Sub Account 
- Wallet
- Info
The package is currently at version 1.1 and is fully documented. The package is available on npm [here](https://www.npmjs.com/package/chimoneyjs)

Preview of Package on npm
0560B531-1AEA-4B4A-B894-80C4E39169A8

### CODE REVIEW

**Comment by uchibeke** [comment]
@Elozzy please review so it aligns with all API changes

**Review by Elozzy — APPROVED** [review]
LGTM 🚀🚀

**Comment by phyleria** [comment]
Hello @Ayo-Awe 
Kindly send your email address as a reply to this comment. You will then receive your hacktoberfest reward via email.
Thank you.

**Comment by Ayo-Awe** [comment]
@phyleria it’s pupoawe@icloud.com

**Comment by phyleria** [comment]
Thank you

**Pull request merged**
