### PR TITLE
Enhance Chimoney Bot by adding maintainer notifications and error handling for payouts.

### PR DESCRIPTION
**Pull request by THEJOHNCALEB**
I've improved the Chimoney GitHub bot's notification system by adding new functions to keep maintainers informed about payout operations. 

Some of the changes include:

- `notifyMaintainerOfPaymentStatus`: A new function that notifies the repository maintainer when a payout is successfully initiated.
- `handlePaymentErrors`: A new function that detects and notifies users of any errors encountered throughout the payout process.
- Modified existing functions for easier maintenance.
- Ensured proper error handling and status updates to improve communication in payout operations.

### CODE REVIEW

**Comment by phyleria** [comment]
Hi @THEJOHNCALEB 

Can you please give an appropriate title to this PR. Thanks!

**Comment by THEJOHNCALEB** [comment]
Done @phyleria

**Comment by phyleria** [comment]
Awesome, thank you @THEJOHNCALEB 

It will be reviewed now ✅

**Review by phyleria — APPROVED** [review]
LGTM 🎉

**Pull request merged**
