### PR TITLE
automate badge distribution based on merged pr activity

### LINKED ISSUE #390: Automate Badge Distribution Based on Merged PR Activity
We want to automate the process of sending badges to contributors whenever their PRs are merged.

> **Please note** that this issue can only be started after the badges have been designed and finalized.

The badges should be delivered in two ways:

1. **Posted as a comment on the merged PR.**
2. **Sent via email** (if the contributor's email is public) with the customized congratulatory message.

#### 1. GitHub Integration:
- Set up GitHub Actions or a bot to automatically post the appropriate badge as a comment when a PR is merged.
- Include the contributor’s GitHub handle in the congratulatory message.

#### 2. Email Automation:
- If the contributor’s email is public, send an email with the badge attached along with the congratulatory message.

### Badge Conditions:
- **First-Time Contributor:** If the contributor is making their first-ever merged PR, send the "First-Time Contributor Badge."
- **Every Merged PR:** For every merged PR (including the first), send the "Every Merged PR Badge."
- **First Four Merged PRs:** Once a contributor hits their fourth merged PR, send the "First Four Merged PRs Badge."

### Custom Messages for Each Badge:

- **First-Time Contributor Badge Message (GitHub Comment and Email):**  
  "🎉 Congratulations on your first contribution! Your PR has been merged, and you’ve earned the First-Time Contributor Badge! Welcome to the Chimoney open-source community, and we can’t wait to see what you’ll build next! 🌟"

- **Every Merged PR Badge Message (GitHub Comment and Email):**  
   "🚀 Congratulations! Your PR has been successfully merged, and here’s your badge for a fantastic contribution. Keep up the great work, and thank you for being a part of the Chimoney community!"

- **First Four Merged PRs Badge Message (GitHub Comment and Email):**  
"🌟 Outstanding achievement! You've successfully merged four PRs! Thank you for your continued contributions to the Chimoney community—we truly appreciate your dedication!"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by adarsh-jha-dev**
Closes #390 

To make the github action work, follow these: 

 Add the following secrets in **Secrets and Variables** on github:
     - `EMAIL_USER`: The email address to send badge notifications from
     - `EMAIL_PASS`: The password or app-specific password for the email account

### CODE REVIEW

**Comment by adarsh-jha-dev** [comment]
Hey @phyleria , please ignore that commits of article [PR](https://github.com/Chimoney/chimoney-community-projects/pull/415), I checked out to this new branch from that [article branch](https://github.com/adarsh-jha-dev/chimoney-community-projects/tree/patch-10) itself, thats why those files are also being shown as modified/added , once you merge that article [PR](https://github.com/Chimoney/chimoney-community-projects/pull/415) first, it will be corrected.

Thank you.

**Review by todak2000 — DISMISSED** [review]

**Comment by adarsh-jha-dev** [comment]
Hey @phyleria , since the PR is approved, I suggest before merging this - please merge that article PR (I'll wait for your changes there) first and then do a "Update branch" here on this PR and then merge it - otherwise the flow will break.

**Comment by phyleria** [comment]
Ok, noted @adarsh-jha-dev

**Comment by adarsh-jha-dev** [comment]
> Ok, noted @adarsh-jha-dev

It'd be nice if you please put the `hacktoberfest-accepted` tag here.

**Comment by phyleria** [comment]
Done ✅

**Comment by adarsh-jha-dev** [comment]
> Done ✅

Thanks , so nice of you.

**Comment by adarsh-jha-dev** [comment]
hey @phyleria , I was just going through my PRs and saw the conflicts (as some of the PRs were merged) as I updated them, the approval got removed- could you please ask @todak2000  to approve it again? (the conflicts where not from any code files - that was just the articles which were added by me). Thank you!

**Comment by phyleria** [comment]
Hi @todak2000,

Please approve @adarsh-jha-dev's PR again. Thanks!

**Review by phyleria — APPROVED** [review]
LGTM 🎉

**Pull request merged**
