### PR TITLE
Chimoney GitHub integration

### PR DESCRIPTION
**Pull request by Ayo-Awe**
@uchibeke I've implemented the changes. I changed it from a GitHub action to a GitHub app to make the setup easier.
You can give it a try by adding the app to any repository via this link https://github.com/apps/chimoneybot

### CODE REVIEW

**Comment by Ayo-Awe** [comment]
* Once a PR is merged, the maintainer will be notified
* You can reward a contributor using the payout slash command e.g
/payout $10
* The bot will reply with a link to reward the contributor (author of PR)

**Comment by Ayo-Awe** [comment]
Thanks, funds received
image

**Comment by Ayo-Awe** [comment]
@uchibeke notifying after payment sounds good, but I'm not sure if I'll be able to implement it in time.

**Comment by uchibeke** [comment]
> Thanks, funds received image

Sounds good. I will go ahead and approve it

**Review by uchibeke — APPROVED** [review]

**Comment by uchibeke** [comment]
@phyleria FYI you can use this bot to reward users for their contribution.

**Pull request merged**
