### PR TITLE
feat: Update README.md

### PR DESCRIPTION
**Pull request by Lymah123**
# This PR makes changes to reame.md.

- This is the latest submission on the issue #251  and
-  #257

### CODE REVIEW

**Comment by Lymah123** [comment]
Hi @phyleria 

Is this what you asked me to do?

**Comment by phyleria** [comment]
Hi @Lymah123 

Your proposed changes seem to interfere with the Project setup flow description. Kindly add it at the end of the Project Setup section.

**Comment by Lymah123** [comment]
> Hi @Lymah123
> 
> Your proposed changes seem to interfere with the Project setup flow description. Kindly add it at the end of the Project Setup section.

Hi @phyleria . Can you check again please. I guessed I have made the changes you mentioned. Let me know if I was wrong.
Thank you.

**Comment by Lymah123** [comment]
Hi @phyleria. Any update?

**Review by phyleria — CHANGES_REQUESTED** [review]
Hi @Lymah123 

Your changes are still interfering with the project setup description. Kindly add them at the end of that section; which ends with `Contribute to the existing projects` sub-section 
Screenshot from 2023-11-02 10-35-18

**Comment by Lymah123** [comment]
Screenshot_20231102-094432_Chrome


Hi @phyleria , I  just added it after `contributing to the existing project` subsection before the `code of conduct `

I will be waiting for your review. Thanks!

**Comment by Lymah123** [comment]
> Screenshot_20231102-094432_Chrome
> 
> Hi @phyleria , I just added it after `contributing to the existing project` subsection before the `code of conduct `
> 
> I will be waiting for your review. Thanks!

Screenshot_20231102-094432_Chrome

**Review by phyleria — CHANGES_REQUESTED** [review]
Great, kindly remove this part too.
Can you indent the `Contribute via Gitpod` title to be on the same line as the rest of the titles? 

On the `Contributing via Codespaces section` this is what shows on my end. Kindly fix the image and link issue. Just these fixes and you'll be done
Screenshot from 2023-11-02 14-44-14

**Comment by Lymah123** [comment]
Hi @phyleria!

I have fixed the indentation.  It shows on my end.

Screenshot_20231102-142153_Chrome

**Comment by phyleria** [comment]
Kindly fix the other issues I mentioned in the previous comment too.

**Comment by Lymah123** [comment]
Hi @phyleria , any update?

**Comment by phyleria** [comment]
> Hi @phyleria , any update?

Kindly fix the other issues I mentioned

**Comment by Lymah123** [comment]
> > Hi @phyleria , any update?
> 
> Kindly fix the other issues I mentioned

Which one please?

**Comment by phyleria** [comment]
> Great, kindly remove this part too. Can you indent the `Contribute via Gitpod` title to be on the same line as the rest of the titles?
> 
> On the `Contributing via Codespaces section` this is what shows on my end. Kindly fix the image and link issue. Just these fixes and you'll be done Screenshot from 2023-11-02 14-44-14

These

**Comment by Lymah123** [comment]
> > Great, kindly remove this part too. Can you indent the `Contribute via Gitpod` title to be on the same line as the rest of the titles?
> > On the `Contributing via Codespaces section` this is what shows on my end. Kindly fix the image and link issue. Just these fixes and you'll be done Screenshot from 2023-11-02 14-44-14
> 
> These

I have fixed the image for codespaces.  It's showing on my end. Is it not showing over there?

**Comment by Lymah123** [comment]
I also linked the issue as well.

**Comment by Lymah123** [comment]
Screenshot_20231103-144238_Chrome

Hi @phyleria , can you see the screenshot. What would you suggest? Or I should remove the codespaces?

**Comment by Lymah123** [comment]
Hi @phyleria , I have checked again. The buttons are showing. Do you have an idea what could be the problem why you are not seeing it over there?

**Comment by Lymah123** [comment]
Hi @phyleria, I have made changes on two different branches. I am seeing changes I made on these branches. I really don't know why it is not showing over there. Let me know what to do to fix that. Thanks!

**Review by phyleria — CHANGES_REQUESTED** [review]
This is what shows on my end @Lymah123 

I suggest you remove the  'To set up your development environment, you can use CodeSpaces or Gitpod:` part and also  the `contributing via codespaces` section.  
Just leave the  `Contributing via Gitpod` section

[CodeSpaces](https://github.com/features/codespaces)
[Gitpod](https://www.gitpod.io/)

**Comment by Lymah123** [comment]
Alright @phyleria,  I will do that.

**Comment by Lymah123** [comment]
@phyleria , I just fixed that.

**Comment by phyleria** [comment]
You've left out this part 
Screenshot from 2023-11-06 15-40-10

**Comment by Lymah123** [comment]
Hi @phyleria , I just fixed that.

**Review by phyleria — APPROVED** [review]
Awesome, thanks for your patience @Lymah123 !

**Comment by Lymah123** [comment]
Hi @phyleria , you have not merged the PR?

**Pull request merged**
