### PR TITLE
[hacktoberfest] Slackbot

### PR DESCRIPTION
**Pull request by thelimeskies**
SlackBot for Chimoney, OAuth2.0 auth flow for app installation.

### CODE REVIEW

**Comment by uchibeke** [comment]
Hi @thelimeskies, how do I test? Could you add to the readme, please?

**Comment by thelimeskies** [comment]
It's currently on local have to deploy today, making it multi workspace was what was causing the trouble 
it would be deployed and the documentation will be push today

**Comment by thelimeskies** [comment]
Screenshot 2022-11-01 at 10 32 11 AM
Screenshot 2022-11-01 at 10 31 54 AM


Above is the bot working

**Comment by uchibeke** [comment]
Hi @thelimeskies  could you update readme to include how to test, run and deploy this and any env variables or setup needed

**Pull request merged**
