### PR TITLE
Fixed the redirection to CONTRIBUTING.md in README.md

### LINKED ISSUE #277: docs: Invalid link to CONTRIBUTING.md
The link given for "Contributing Guidelines" (CONTRIBUTING.md) in the README.md is an invalid one. I have attached a screenshot of the same : 

Screenshot 2023-10-23 131743

##Reproduction Steps
Replace the link in README.md with the correct one.

### PR DESCRIPTION
**Pull request by adarsh-jha-dev**
After going through the README.md, i found that the link to CONTRIBUTING.md wasn't responding and looking into it, i found there was no valid link provided for the same. I fixed it by placing the correct link of CONTRIBUTING.md.

Fixes #277

### CODE REVIEW

**Comment by phyleria** [comment]
Please reference the issue number @adarsh-jha-dev

**Comment by adarsh-jha-dev** [comment]
> Please reference the issue number @adarsh-jha-dev

There are no existing issues for this

**Comment by phyleria** [comment]
Kindly create the issue first for review.

**Comment by adarsh-jha-dev** [comment]
I have created an issue and mentioned the same in the PR

**Comment by adarsh-jha-dev** [comment]
Hey @phyleria thanks for adding the hacktoberfest lable, could you please review this PR and merge it if you're satisfied with the changes?

**Review by phyleria — APPROVED** [review]
LGTM

**Pull request merged**
