### PR TITLE
[hacktoberfest] feat: Implement chimoney discord bot

### PR DESCRIPTION
**Pull request by Ayo-Awe**
I've implemented a slash command to initiate payouts on discord @ issue #61

@uchibeke I've setup the slash command. See  below 

Screenshot 2022-10-22 215802
Screenshot 2022-10-22 215847
Screenshot 2022-10-22 220212
Screenshot 2022-10-22 220236
image

### CODE REVIEW

**Comment by Ayo-Awe** [comment]
@uchibeke I've setup the command, see pull request #67

**Comment by uchibeke** [comment]
Great.

Please set up Webhook in the [Developer page](https://dash.chimoney.io/developers) and subscribe to the `chimoney.payment.completed` event

You can use https://webhook.site/ to see if you get the event after you make the payment from your wallet

If you're getting the message from the webhook, implement your own endpoint that receives the webhook message and data
- Verify that is coming from Chimoney
- Use the issueID to get the transaction
- Confirm it is `paid` on the Chimoney side
- Check chimoney.meta and then get and notify `chimoney.meta.discordReciever` and `chimoney.meta.discordSender` on Discord. Sample message to to the receiver is similar to what you get in your DM on twitter with the redeem link

Hope this helps? And please let me know if you have any questions

**Comment by uchibeke** [comment]
Do you need help with this @Ayo-Awe ?

**Comment by Ayo-Awe** [comment]
Hey @uchibeke , yes I'm having some troubles with the webhook events. The "payout.chimoney.completed" event is only triggered when the transaction has been paid for and redeemed. What I need is an event that is triggered only when the transaction has been paid for

**Comment by Ayo-Awe** [comment]
so far I haven't gotten any event on chimoney.payment.completed

**Comment by Ayo-Awe** [comment]
@uchibeke I'm waiting on you for more info about the webhooks, what webhook event is fired on successful payment

**Comment by Ayo-Awe** [comment]
@uchibeke I've successfully setup the discord bot

**Comment by uchibeke** [comment]
@Ayo-Awe how to test on discord?

**Comment by Ayo-Awe** [comment]
@uchibeke you can add the bot to your discord server using this [link](https://discord.com/api/oauth2/authorize?client_id=1033109520114798653&permissions=414464859200&scope=bot). Then you can use the slash command /send_chimoney and supply the required options. I've included a readme too

**Comment by uchibeke** [comment]
Hi @Ayo-Awe I was able to install the bot. 🚀 

But the application did not respond to the command

Could you take a look?
Screen Shot 2022-10-31 at 8 44 14 PM

Also, do you mind sharing a screen recording of the payment link issue, from clicking on discord to when you get the error?

**Comment by Ayo-Awe** [comment]
@uchibeke the issue is with the deployment, heroku servers timeout after a few minutes of inactivity. I’ll share a recording soon.

I need to find alternative deployment. One that is continuously running and that allows me to expose an API. Heroku worker doesn’t expose port but the heroku web process times out after a few minutes.

for the sake of testing, you can click this [link](https://chimoney-discord-bot.herokuapp.com) to get the bot live until I find an alternative. The link itself doesn’t do anything but it wakes up(for lack of a better word) the herokuapp

**Comment by Ayo-Awe** [comment]
@uchibeke here’s the link to the video you requested. [DemoVideo](https://drive.google.com/file/d/1tCAOc3B6V5vIJueSln9sqMheH67kmdYo/view?usp=drivesdk)

**Comment by uchibeke** [comment]
@Ayo-Awe please try render.com. It's easy to set up

Also, the link you sent returns error

**Comment by Ayo-Awe** [comment]
@uchibeke I know the link returns error, it's just to kickstart the heroku api to get the bot live. I've taught of trying render but render's worker service is paid but I'll look further into it. 
Once you've clicked the link, next time you check the bot, it should be live, then you can test it.

**Comment by uchibeke** [comment]
@Ayo-Awe tested and was able to generate and pay for the Chimoney

However, it goes to your email instead of the email of the discord user. Could you fix this?

**Comment by Ayo-Awe** [comment]
@uchibeke you mentioned that I should use the turnOffNotification flag when initating the payment since I couldn't get the discord user's email. A payment link should have been sent to the DM of the receiver

**Comment by uchibeke** [comment]
@Ayo-Awe got it. Yes I got the Discord DM with the redeem Link

Some things to consider:
- Do not show ChiRef to the Sender
- You can call /initiate-chimoney without email or twitter. We have changed that endpoint to not require it


Question: did you get the email notification for the $1s I sent? Even with the turnOffNotification?

**Comment by Ayo-Awe** [comment]
@uchibeke 
Noted, I'll get rid of the chiRef and I'll update the chimoneyjs package to make the email optional.

I didn't get the email notification

**Review by uchibeke — APPROVED** [review]

**Pull request merged**
