### PR TITLE
[Docs] - Customise the Readme file

### PR DESCRIPTION
**Pull request by Ajiboso-Adeola**
A fix to issue #252 ,

- I added the Chimoney logo to the readme file

- Add the Twitter link 🖇️ to the mode of Communication in the Readme file

- Enhanced the readme file

### CODE REVIEW

**Review by phyleria — CHANGES_REQUESTED** [review]
Hi @Ajiboso-Adeola 

Please change this `The Open-Source Multiple Payment Rail` to `Chimoney Community Projects`

**Comment by Ajiboso-Adeola** [comment]
changes made @phyleria

**Comment by SamsShow** [comment]
I noticed that the updated file documentation is not written in Markdown
I'm linking a proper md update below

**Comment by Ajiboso-Adeola** [comment]
> I noticed that the updated file documentation is not written in Markdown I'm linking a proper md update below

It was written in Markdown

**Comment by SamsShow** [comment]
This i not proper MD
image

**Comment by Ajiboso-Adeola** [comment]
> This i not proper MD image

I think you are referring to the way I used HTML tags in the readme file, 

HTML tags can be used in markdown file as well

**Review by phyleria — APPROVED** [review]
LGTM 🎉

**Pull request merged**
