### PR TITLE
blog on how to get started with chimoney api

### PR DESCRIPTION
**Pull request by Davidongora**
completed creating an intuitive blog that also allows beginners to understand how they can create a developer account and start testing out and integrating with our API

### CODE REVIEW

**Comment by phyleria** [comment]
Hey @Davidongora thanks for working on this.

Could you please publish the blog on our hashnode community blog [here](https://community-chimoney.hashnode.dev/). Join the team [here](https://hashnode.com/teams/invite/b0bdf4a4-4dd4-408f-8d7a-a24d5d6729e1). Kindly let me know when  this is done.

**Review by phyleria — CHANGES_REQUESTED** [review]
Hi @Davidongora the Chimoney API is a single API. Please correct this and other lines that signify that Chimoney has a range of APIs

**Comment by Davidongora** [comment]
i have made the changes

**Review by phyleria — COMMENTED** [review]
HI @Davidongora please edit this section too

**Review by phyleria — COMMENTED** [review]
And this section.

**Review by phyleria — COMMENTED** [review]
This part needs editing too

**Review by phyleria — COMMENTED** [review]
There's another typo here too. Please review the whole blog and turn all the 'APIs' to API

**Review by phyleria — APPROVED** [review]
LGTM

**Pull request merged**
