### PR TITLE
Create README-JP.md

### PR DESCRIPTION
**Pull request by HarshMN2345**
Japanese translation of the Chimoney Hacktoberfest 2023 guide.

### CODE REVIEW

**Comment by HarshMN2345** [comment]
can any reviewer please review this?

**Comment by HarshMN2345** [comment]
@phyleria please review this

**Review by phyleria — CHANGES_REQUESTED** [review]
Hi @HarshMN2345 

Some changes have been made since you last made the changes. Kindly pull them first to avoid conflicts.

**Comment by HarshMN2345** [comment]
@phyleria done

**Comment by HarshMN2345** [comment]
@phyleria Please let me know that if is it good to go?

**Review by phyleria — APPROVED** [review]

**Pull request merged**
