### PR TITLE
[hacktoberfest] payout airtime project completed

### PR DESCRIPTION
**Pull request by mzoyinda**
[hacktoberfest] redeem airtime [Link to referred issue](https://github.com/Chimoney/chimoney-community-projects/issues/36)

### CODE REVIEW

**Comment by uchibeke** [comment]
Could you remove all the .DS_Store files or add **/**/.DS_Store to your .gitignore file

I see two folders for the Airtime submission. Which one do you want to submit? Could you have all your code in one folder in the submissions folder?

Looking forward to reviewing it @mzoyinda

**Comment by mzoyinda** [comment]
Thanks for pointing out the errors, i have removed all the .DS_Store files and removed the multiple payout folder.

**Review by uchibeke — APPROVED** [review]
LGTM ♠️

**Comment by Elozzy** [comment]
> I have approved it
> 
> Some things
> 
> * How are you managing the API keys? Because the live version says the API key in invalid
> * The UI on mobile is broken. Could you make it responsive?
> 
> Screen Shot 2022-10-24 at 1 58 22 PM

@mzoyinda Kindly attend to these changes.

**Comment by mzoyinda** [comment]
Yeah, i had to remove the API keys for security reasons.
But I think the remaining $6 in my account for testing has been removed totally by the admin,
wanted to send a mail for that though.. 

So since it is currently empty, I can add the real API Keys, but still, nothing would be paid out ooo
as the account is empty.

**Comment by mzoyinda** [comment]
I'd also fix the mobile responsiveness

**Comment by uchibeke** [comment]
Please do not hardcode the key. Use environment variables or a config file. There a a few ways to do it if you search Google but let me know if o can help clarify 

also, consider using the /payout/initiate-chimoney endpoint then after it’s successful, redirect to paymentLink from the response. This ensures that anyone can use your app to send Chimoney and they pay from their own Chimoney wallet, not yours, since initiate-Chimoney creates a transaction without paying for it. Pass phoneNumber, country into the redeemData field as outlined in the redeem/any endpoint 

happy to clarify when I’m on my laptop 

The api key gives you access to the api to initiate the payment

**Comment by mzoyinda** [comment]
Oh.. i just tried out your suggestion on the docs and that can work too
But it would be changing the whole project from payout airtime to payout chimoney.
Also, the payment link I got after the request was successful is taking forever to load. (if you can look into that.)

So what happens after the payment link loads.. would like to know the flow.

**Comment by uchibeke** [comment]
Hi @mzoyinda, could you try the Payment link again? Fixed

**Comment by mzoyinda** [comment]
Hi @uchibeke you can check out the updated project for changes

**Pull request merged**
