### PR TITLE
[Hacktoberfest]Create updated copy of Chimoney

### PR DESCRIPTION
**Pull request by adeola-dev**
This PR was made to address the issue #9

### CODE REVIEW

**Comment by uchibeke** [comment]
Thoughts on this @Regedit-msc ?

**Review by Regedit-msc — APPROVED** [review]

**Comment by phyleria** [comment]
Hello @adeola-dev 
Kindly send your email address as a reply to this comment. You will then receive your hacktoberfest reward via email.
Thank you.

**Comment by adeola-dev** [comment]
Hello,

My email address is ***@***.***

Thank you.

**Comment by phyleria** [comment]
Thank you

**Pull request merged**
