### PR TITLE
[Hacktoberfest] Chiconnect Laravel Web App

### PR DESCRIPTION
**Pull request by codelikesuraj**
# Chiconnect Laravel Web App

## Available features

- User creates a unique username on signup
- User gets a new sub_account on signup (+ wallets - chi, airtime & momo)

chidash

- Users can send chi-money to other users using their username

dash2

- Users can send money (bank payout) to any supported bank in any supported country

chibank

- Users can send airtime (airtime payout) to any phone number in supported countries

chiairtime

- Users can view all transfers (debit or credit) on their account

chitransfer

- Users can also view all payouts (bank and airtime) made from their account

chipayout-all

 ### Issue: #16

### CODE REVIEW

**Comment by codelikesuraj** [comment]
@uchibeke

Click this link to view it live [Chiflex](http://chiflex.herokuapp.com/dashboard) hosted on heroku

Note: you can use a fake email and please use a password thats easy to remember as I have not implemented the password reset feature on the app yet

Kindly reply this comment with the username you used on the app so I can transfer money to you.

**Comment by uchibeke** [comment]
I get internal server error. Could you test the app by registering new account and ensure it all works? @codelikesuraj

**Comment by codelikesuraj** [comment]
> I get internal server error. Could you test the app by registering new account and ensure it all works? @codelikesuraj

I already looked into that. Everything's okay now. sorry about that

**Comment by uchibeke** [comment]
> > I get internal server error. Could you test the app by registering new account and ensure it all works? @codelikesuraj
> 
> I already looked into that. Everything's okay now. sorry about that. I think the problem arose because the email you registered with might already exist on chimoney itself.
> 
> My app creates a new sub-account by sending the user's name & email as parameters to the chimoney API endpoint, which returns a payload containing the sub_account_id.
> 
> This might be a huge problem though. This kinda means that if an email is already registered as a sub-account on another application (utilizing chimoney's api), it means they won't be able to use the same email on another chimoney-backed application.

Great catch! You’re right. The email is used by an existing account. Sub accounts are regular accounts with a parent

So if we made an existing account a sub account of an organization or a team, it means the parent could use all its balance

Also, if an email is already used by a sub account, and an actual user is trying to create an account with it, that is log in. There might also be an issue

We will update the implementation of sub accounts. Maybe sub accounts don’t need to have an email because you don’t want to be notifying a user of another app from Chimoney. Only the parent account should receive communication from Chimoney

Thanks again for catching this

**Comment by codelikesuraj** [comment]
> > > I get internal server error. Could you test the app by registering new account and ensure it all works? @codelikesuraj
> > 
> > 
> > I already looked into that. Everything's okay now. sorry about that. I think the problem arose because the email you registered with might already exist on chimoney itself.
> > My app creates a new sub-account by sending the user's name & email as parameters to the chimoney API endpoint, which returns a payload containing the sub_account_id.
> > This might be a huge problem though. This kinda means that if an email is already registered as a sub-account on another application (utilizing chimoney's api), it means they won't be able to use the same email on another chimoney-backed application.
> 
> Great catch! You’re right. The email is used by an existing account. Sub accounts are regular accounts with a parent
> 
> So if we made an existing account a sub account of an organization or a team, it means the parent could use all its balance
> 
> Also, if an email is already used by a sub account, and an actual user is trying to create an account with it, that is log in. There might also be an issue
> 
> We will update the implementation of sub accounts. Maybe sub accounts don’t need to have an email because you don’t want to be notifying a user of another app from Chimoney. Only the parent account should receive communication from Chimoney
> 
> Thanks again for catching this

Awesome.
Also I might have incidentally caught a serious bug. I don't think its something that can be discussed publicly. Please reach out via email (codelikesuraj@gmail.com) so we can I can explain further.

**Comment by uchibeke** [comment]
> > > > I get internal server error. Could you test the app by registering new account and ensure it all works? @codelikesuraj
> > > 
> > > 
> > > I already looked into that. Everything's okay now. sorry about that. I think the problem arose because the email you registered with might already exist on chimoney itself.
> > > My app creates a new sub-account by sending the user's name & email as parameters to the chimoney API endpoint, which returns a payload containing the sub_account_id.
> > > This might be a huge problem though. This kinda means that if an email is already registered as a sub-account on another application (utilizing chimoney's api), it means they won't be able to use the same email on another chimoney-backed application.
> > 
> > 
> > Great catch! You’re right. The email is used by an existing account. Sub accounts are regular accounts with a parent
> > So if we made an existing account a sub account of an organization or a team, it means the parent could use all its balance
> > Also, if an email is already used by a sub account, and an actual user is trying to create an account with it, that is log in. There might also be an issue
> > We will update the implementation of sub accounts. Maybe sub accounts don’t need to have an email because you don’t want to be notifying a user of another app from Chimoney. Only the parent account should receive communication from Chimoney
> > Thanks again for catching this
> 
> Awesome. Also I might have incidentally caught a serious bug. I don't think its something that can be discussed publicly. Please reach out via email ([codelikesuraj@gmail.com](mailto:codelikesuraj@gmail.com)) so we can I can explain further.

Emailed you 😂🙏🏾

**Comment by codelikesuraj** [comment]
@uchibeke @Elozzy I think I'm ready for a review now. Do I need to create an issue, I see other contributors doing it but I don't know how and why

**Comment by Elozzy** [comment]
LGTM 🚀🚀

**Review by Elozzy — APPROVED** [review]

**Pull request merged**
