### PR TITLE
[hacktoberfest] feat: Implement giftcard payout api

### PR DESCRIPTION
**Pull request by ezechuka**
This PR integrates Chiconnect giftcard payout api in a simple React app at issue https://github.com/Chimoney/chimoney-community-projects/issues/2

image

### CODE REVIEW

**Comment by uchibeke** [comment]
Could you deploy it on render.com, vercel or heroku so we can test?

**Comment by ezechuka** [comment]
Noted!

**Review by uchibeke — CHANGES_REQUESTED** [review]
- The amount should be from the list of amounts for that Gift card. Users should pick from the fixed amounts
- Countries code is already picked in the top section so should not be changeable in the bottom
- Make the App responsive for mobile and other device sizes
- Make the app flexible so it does not debit from your account. When they click send, call /payout/initiate-chimoney with redeemData set to 
```
      {
          "countryCode": "US",
          "productId": "1"
      }

```
- Then redirect users to to using the Payment link you get from the response

**Comment by ezechuka** [comment]
Noted! 🥲

**Comment by ezechuka** [comment]
@uchibeke does it mean I shouldn't use payouts/gift-card anymore?

>     * Make the app flexible so it does not debit from your account. When they click send, call /payout/initiate-chimoney with redeemData set to
> 
> 
> ```
>       {
>           "countryCode": "US",
>           "productId": "1"
>       }
> ```
> 
>     * Then redirect users to to using the Payment link you get from the response

**Comment by uchibeke** [comment]
> @uchibeke does it mean I shouldn't use payouts/gift-card anymore?
> 
> > ```
> > * Make the app flexible so it does not debit from your account. When they click send, call /payout/initiate-chimoney with redeemData set to
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >       {
> >           "countryCode": "US",
> >           "productId": "1"
> >       }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > * Then redirect users to to using the Payment link you get from the response
> > ```

If you're using payouts/gift-card, that means you pr the person that deployed the app is paying for it from the wallet balance. We want anyone to be able to use the live version of this app. So payouts/initiate-chimoney is the way to go. What do you think?

**Comment by ezechuka** [comment]
Okay I get the point now. Your approach sounds better 👍🏿

**Comment by ezechuka** [comment]
https://chiconnect-giftcard-payout.vercel.app/

@uchibeke this is how `initiate-chimoney` request params looks like below & for some reason the payment link does not work after I sign in.
```
{
    "chimoneys": [{
        "email": "ezechuka9@gmail.com", 
        "valueInUSD": 1,
        "redeemData": {
            "productId": 1,
            "countryCode": "NG"
        }
    }]
}
```

**Review by uchibeke — APPROVED** [review]
LGTM

**Pull request merged**
