### PR TITLE
Update: obtaining api-keys

### PR DESCRIPTION
**Pull request by Lymah123**
## This PR make changes to Readme.md.
 Obtaining API keys section url updated.
- #138

### CODE REVIEW

**Comment by Lymah123** [comment]
@phyleria , I have made update to the issue merged in this PR. I will be waiting for review.

**Review by dk3775 — APPROVED** [review]

**Comment by phyleria** [comment]
Hi @Lymah123 

The link you've provided for developer account signup is not correct. Here is the correct one: https://sandbox.chimoney.io/developers

**Comment by Lymah123** [comment]
> Hi @Lymah123
> 
> The link you've provided for developer account signup is not correct. Here is the correct one: https://sandbox.chimoney.io/developers
> 
> Kindly edit that.

Hi @phyleria , fixed.

**Review by phyleria — APPROVED** [review]
LGTM 🎉

**Pull request merged**
