### PR TITLE
[hacktoberfest] Web P2P app landing page

### PR DESCRIPTION
**Pull request by ezechuka**
This PR resolves the issue #47.
Live URL: https://pay-paddy.vercel.app/

The `sub-account/create` endpoint throws an error currently.

image

### CODE REVIEW

**Comment by uchibeke** [comment]
@ezechuka ` sub-account/create` has now been fixed. Only the sub account name is required.

**Comment by ezechuka** [comment]
@uchibeke the PR has been updated & signup/login works correctly. I would like a review please.

**Comment by uchibeke** [comment]
@ezechuka i tested. Sign in and sign up doesn’t work using the link above

**Comment by ezechuka** [comment]
For some reason the first link was not reflecting the changes, please try this one ==> https://pay-paddy-ezechuka.vercel.app/

**Review by uchibeke — APPROVED** [review]
LGTM ♠️ .

Could you have the Gift card one in another PR?

**Comment by ezechuka** [comment]
The giftcard payout is in a separate PR #63

**Comment by uchibeke** [comment]
> The giftcard payout is in a separate PR #63

Merged that. Could you update the code from your branch after rebasing from this main and then push again? Might need to force push to your branch

Currently, the gift card code is still in this branch

**Comment by ezechuka** [comment]
> > The giftcard payout is in a separate PR #63
> 
> Merged that. Could you update the code from your branch after rebasing from this main and then push again? Might need to force push to your branch
> 
> Currently, the gift card code is still in this branch

Thank you very much for the suggestion 👍🏿 . The branch has been updated

**Review by uchibeke — APPROVED** [review]

**Pull request merged**
