### PR TITLE
Created pull_request_template.md

### LINKED ISSUE #292: [Feature]  Adding Pull Request Template for Chimoney Organization
**Issue Description:**

As a contributor to the Chimoney organization, I have identified the need to implement a standardized Pull Request (PR) template. This PR template will help streamline the contribution process and improve the overall quality of contributions. In this issue, I propose creating a PR template and outline the steps required to implement it.

**Issue Details:**

1. **Problem Statement**: Currently, contributors may not be following a consistent format when creating PRs. This can make it challenging for maintainers to review and merge PRs efficiently.

2. **Proposed Solution**: Create a PR template that contributors must fill out when submitting a PR. This template will include sections for a concise description, related issues, and any additional context necessary for a clear and efficient review.

3. **Benefits**:
    - **Consistency**: Ensure that all PRs follow a standard format, making it easier for maintainers to understand the changes being proposed.
    - **Efficiency**: Streamline the review process by providing the necessary information upfront.
    - **Clarity**: Make it easier for contributors to provide the relevant context and information.
    
4. **Steps to Implement**:
    - [ ] **Design Template**: Design a PR template that includes relevant sections (e.g., description, related issues, checklist).
    - [ ] **Repository Configuration**: Add the PR template to the Chimoney organization's repository.
    - [ ] **Documentation**: Update the organization's contribution guidelines to mention the use of the PR template.

### PR DESCRIPTION
**Pull request by vinfinity7**
Fixes #292 
Created the pull_request_template.md file to standardize PR submissions within the Chimoney organization. This template streamlines PRs by ensuring contributors provide essential information, enhancing the review process. The addition of this template aligns with our goal of improving collaboration and maintaining code quality. Please review and merge.

### CODE REVIEW

**Comment by vinfinity7** [comment]
Kindly Review @phyleria

**Review by phyleria — CHANGES_REQUESTED** [review]
Hi @vinfinity7 

Consider modifying this to:
### Pull Request Details

- **Issue**: 
- **Type**: 
- **Description**:

**Comment by vinfinity7** [comment]
> Hi @vinfinity7
> 
> Consider modifying this to:
> 
> ### Pull Request Details
> * **Issue**:  (Link to the issue the PR addresses)
> * **Type**: (New feature/Enhancement/Fix/Documentation/Other (please specify)
> * **Description**: (A brief description of the PR, what it does, and why it's needed)

Should i drop the checklist or keep it ?

**Review by phyleria — CHANGES_REQUESTED** [review]
To make the checklist more intuitive, I suggest these changes:

##Checklist ✅ 
Please check each item that you have completed for this PR:

- [ ] I have read and understood the project's [Contribution Guidelines](https://chimoney--community.hashnode.dev/contributing-to-chimoneys-community-projects-repository-for-hacktoberfest)
- [ ] I have tested my changes to ensure they work as expected.
- [ ] I have added/updated relevant documentation/screenshots (if applicable).
- [ ] I have included tests (if applicable).
- [ ] I have labeled the PR appropriately with `Feature`, `Improvement`, or `Bug`
- [ ] My branch is up to date with the main branch.
- [ ] The PR has a meaningful title and description.

**Comment by vinfinity7** [comment]
> To make the checklist more intuitive, I suggest these changes:
> 
> ## Checklist ✅
> Please check each item that you have completed for this PR:
> 
> * [ ]  I have read and understood the project's [Contribution Guidelines](https://chimoney--community.hashnode.dev/contributing-to-chimoneys-community-projects-repository-for-hacktoberfest)
> * [ ]  I have tested my changes to ensure they work as expected.
> * [ ]  I have added/updated relevant documentation/screenshots (if applicable).
> * [ ]  I have included tests (if applicable).
> * [ ]  I have labeled the PR appropriately with `Feature`, `Improvement`, or `Bug`
> * [ ]  My branch is up to date with the main branch.
> * [ ]  The PR has a meaningful title and description.

Kindly review the changes @phyleria

**Comment by vinfinity7** [comment]
@phyleria consider merging

**Review by phyleria — CHANGES_REQUESTED** [review]
Kindly change this to:

## Pull Request Details

**Review by phyleria — CHANGES_REQUESTED** [review]
Edit this to:


#### Issue Number:

#### Issue Type:
- [ ] Feature
- [ ] Improvement
- [ ] Bug
- [ ] New Project

#### PR Description:

**Review by phyleria — CHANGES_REQUESTED** [review]
Add 4 hashes for a smaller heading

**Comment by vinfinity7** [comment]
@phyleria Done

**Comment by vinfinity7** [comment]
@phyleria how do you handle payouts after pr is merged ?

**Pull request merged**
