### PR TITLE
[hacktoberfest]feat: implemented MapBox for showing supported products/countries in a map 

### PR DESCRIPTION
**Pull request by tobiadiks**

### CODE REVIEW

**Comment by Regedit-msc** [comment]
Please add a sample video showcasing the application.

**Comment by tobiadiks** [comment]
> Please add a sample video showcasing the application.

Noted

**Comment by tobiadiks** [comment]
@Regedit-msc  here's the video

https://youtu.be/sGEQkWpBB-Q

**Comment by tobiadiks** [comment]
@uchibeke here's is the video showcase

**Comment by uchibeke** [comment]
@tobiadiks some things I’ll consider
- use dark theme for the map and app or have a toggle to switch between both. See inspiration from stripe website and xrptree https://stripe.com/  https://threexrp.dev/ 
- add the country flag to the title of the popup. Use an emoji or use the country-flags npm package


These aren’t a big deal but will make it look much better

**Comment by tobiadiks** [comment]
Noted @uchibeke

**Comment by uchibeke** [comment]
@tobiadiks done with the updates?

**Comment by tobiadiks** [comment]
Will push them updates today

**Comment by tobiadiks** [comment]
@uchibeke 
i have pushed it.
here's the update

https://youtu.be/HPFZgM1YnT0

**Review by uchibeke — APPROVED** [review]
LGMT ♠️ 

Do you want to deply it somewhere like render.com? Or Vercel? Heroku? And share the link? Maybe add it to the readme

**Comment by tobiadiks** [comment]
> LGTM ♠️
> 
> Do you want to deply it somewhere like render.com? Or Vercel? Heroku? And share the link? Maybe add it to the readme

Thank you @uchibeke I will deploy it on vercel and make the update on the readme today.

**Comment by tobiadiks** [comment]
Done @uchibeke 
https://chimoney-map.vercel.app/

**Comment by uchibeke** [comment]
Looks great!

Mising gift cards. Maybe open an issue and a different pr to add gift cards

So the assets info endpoint takes a countryCode which pulls the gift cards for that country and returns it as part of the response. Could you include that to this map?

potentially when someone clicks a country, call that endpoint and replace or add the gift card list to the list of shown items in its own section.

**Comment by tobiadiks** [comment]
Sounds good @uchibeke . Yes I can add it to the map, just to clarify, the gift card feature isn't available for all countries right?

**Comment by uchibeke** [comment]
For most countries you will get a gift card. Pass the 2-digit iso county code to the endpoint and the returned gift card will be for the currently selected country

Something else, for mobile money, there is also a momo list, consider using that to expand the mobile money list as its own section 

crypto should be the last section and products second to last

**Comment by tobiadiks** [comment]
Noted @uchibeke will create an issue and make the proposed updates.

**Pull request merged**
