### PR TITLE
Create README-GM.md

### PR DESCRIPTION
**Pull request by HarshMN2345**
Added german translation for hacktoberfest guide 2023

### CODE REVIEW

**Comment by HarshMN2345** [comment]
@phyleria please review this

**Comment by HarshMN2345** [comment]
@uchibeke please review this

**Review by uchibeke — APPROVED** [review]

**Comment by uchibeke** [comment]
@HarshMN2345 please fix conflict

**Comment by HarshMN2345** [comment]
@uchibeke  done

**Review by uchibeke — APPROVED** [review]

**Pull request merged**
